- hosts: webservers
  tasks:
      - name: Install EPEL release for nginx
        yum: name=epel-release state=present 
        become: yes
        become_user: su

      - name: Install nginx web server
        yum: name=nginx state=installed update_cache=true
        become: yes
        become_user: su

      - name: Start Nginx
        service: name=nginx state=started enabled=yes

      - name: Create webadmin user  
        user:
          name: "webadmin"
          comment: "Web Admin User"  
          groups: nginx

      - name: Create www directory
        file:
          path: /var/www/explorecalifornia
          state: directory
          mode: '0775'
          owner: "webadmin"
          group: "webadmin"

      - name: Copy Web files from GitHub
        copy:
          src: 'https://github.com/cbbics/explorecalifornia.git'
          dest: '/var/www/explorecalifornia'
