
- hosts: webservers

  tasks:
  - name: Install Nginx
    yum: name=nginx state=present

  - name: Start Nginx
    service: name=nginx state=started enabled=yes

  - name: Create webadmin user  
    user:
      name: "webadmin"
      comment: "Web Admin User"  
      groups: nginx

  - name: Create www directory
    file:
      path: /var/www/explorecalifornia
      state: directory
      mode: '0775'
      owner: "webadmin"
      group: "webadmin"

  - name: Copy Web files from GitHub
    copy:
      src: 'https://github.com/cbbics/explorecalifornia.git'
      dest: '/var/www/explorecalifornia'
      # owner: root
      # group: root
      # mode: '0600'

  # - name: delete default nginx site
  #   file:
  #     path: /etc/nginx/sites-enabled/default
  #     state: absent
  #   notify: restart nginx

  # - name: copy nginx site.conf
  #   template:
  #     src: site.conf.j2
  #     dest: /etc/nginx/sites-enabled/{{ domain }}
  #     owner: root
  #     group: root
  #     mode: '0644'
  #   notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted